### ISSUE TITLE
Add to README info on allowing long-lived tabula processes or extracting multiple areas at once

### ISSUE THREAD

**Issue by vitorbaptista** [tabulapdf/tabula-java#82]
I'm parsing PDFs with multiple tables (>10), so I have to run `tabula` multiple times for each PDF. I wonder how much of the time spent by Tabula is because of the startup costs of loading the JVM and reading the file, and how much is actually extracting the data.

Are there any plans on improving this use case (multiple tables per PDF file)? Or are there any hints on best practices when dealing with thousands/millions of files?

**Comment by jeremybmerrill** [comment]
Hi @vitorbaptista, yes, JVM start-up time is a lot of the cost of the `tabula` command. There are a few options discussed in https://github.com/tabulapdf/tabula-java/issues/75: 

- the `drip` utility 
- the Ruby and R bindings 
- writing your own program that imports tabula-java.

Eventually, to answer your question more directly, we do want to create an HTTP API for extracting multiple tables with one Tabula process. (This already exists in the Tabula GUI app, but needs to be separated out.) 

I should add this question to our README, because I suspect you're not the only person wanting to know the answer...

**Comment by vitorbaptista** [comment]
Thanks for your quick answer, @jeremybmerrill. I didn't know about `drip`, but it sounds very interesting. Unfortunately, it ended up being slower than just calling `java` directly in my tests, not sure why :/

You said the Tabula GUI already uses an API? Is it documented anywhere?

**Comment by jeremybmerrill** [comment]
Interesting... @jazzido, do you know anything more about `drip`? 

Yes, the Tabula GUI uses an API. It's not really documented anywhere: basically, you have to put the PDF in the right folder, then you're just posting a set of coordinates and an extraction method to the endpoint. It's on the roadmap to be [separated out](https://github.com/tabulapdf/tabula-api), but we're not there yet.

**Comment by vitorbaptista** [comment]
Have you guys thought about accepting multiple `--area` values in the command line app? It still requires a JVM start for each file, but it can improve the speed quite a bit. The main issue I see is how to structure the output so the user can get the result for each area. Maybe a JSON keyed by the `area`? Or an array with the same order as the areas that were passed?

**Comment by jeremybmerrill** [comment]
That's definitely a possibility. We'll try to come up with a better solution to avoid the JVM startup problem. I suppose the `tabula` executable could parse the script you download instead of executing it in bash.

**Comment by vitorbaptista** [comment]
Thanks a lot for your help. I'll work with the suggestions you gave me. Writing a small wrapper around `CommandLineApp` to parse multiple `--area`s at once have already gave me good results :beers:
